name: Python FastAPI CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install fastapi uvicorn pytest flake8

      - name: Lint with flake8
        run: |
          pip install flake8
          flake8 . --exclude=venv --count --select=E9,F63,F7,F82 --show-source --statistics


      - name: Run unit tests
        run: |
          pytest 
